# Generated by Django 4.2.8 on 2023-12-06 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('zone', models.CharField(blank=True, choices=[('EASTERN', 'EASTERN'), ('WESTERN', 'WESTERN'), ('SOUTHERN', 'SOUTHERN'), ('NORTHERN', 'NORTHERN')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sn', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('tollFree', models.CharField(blank=True, max_length=15, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state'),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('caseNo', models.CharField(max_length=100)),
                ('ch', models.IntegerField()),
                ('filed', models.DateTimeField(blank=True, null=True)),
                ('discharged', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=350)),
                ('zip', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.state')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
