# Generated by Django 4.2.8 on 2024-02-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_no',
            field=models.CharField(max_length=100),
        ),
    ]
