# Generated by Django 4.2.8 on 2024-02-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('date_created',)},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='date_send',
            new_name='date_created',
        ),
    ]
